steps:
  # 1. Install Dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install', '-g', 'pnpm']
  - name: 'node:20'
    entrypoint: 'pnpm'
    args: ['install']

  # 2. Lint & Type Check (Parallel via Turbo)
  - name: 'node:20'
    entrypoint: 'pnpm'
    args: ['turbo', 'run', 'lint', 'build', '--filter=backend-api', '--filter=@monorepo/shared']
    # Note: 'build' here acts as type-check since it runs tsc

options:
  logging: CLOUD_LOGGING_ONLY
